name: $(Version).$(rev:r)

variables:
- name: Version
  value: '1.0.0'

trigger:
  branches:
    include:
    - master

pr: none

stages:
- stage: BuildWithoutTemplate
  displayName: 'Build without Template'
  jobs:
  - job: HostedVs2017
    displayName: 'Hosted VS2017'
    pool:
      name: 'Hosted VS2017'
    workspace:
      clean: all
    variables:
    - name: Greeting
      value: 'Hello World'
    steps:
    - task: CmdLine@2
      displayName: 'Echo Greeting in CommandLine'
      inputs:
        script: 'Echo $(Greeting)'
    - task: PowerShell@2
      displayName: 'Echo Greeting in PowerShell'
      inputs:
        targetType: Inline
        script: 'Write-Host "$(Greeting)"'
