parameters:
  templateLevel: ''
  agentName: ''
  message: ''

stages:
- stage: ReleaseWithNestedStagesTemplate
  displayName: 'Release with Nested Stages Template'

  jobs:
  - template: 'template-jobs-nested-release.yaml'
    parameters:
      templateLevel: '${{ parameters.templateLevel }}'
      agentName: '${{ parameters.agentName }}'
      message: '${{ parameters.message }}'
