parameters:
  templateLevel: ''
  message: ''

jobs:
- deployment: HostedVs2017
  displayName: 'Hosted VS2017'

  pool:
    name: 'Hosted VS2017'

  environment: release-with-${{ parameters.templateLevel }}-template

  strategy:
    runOnce:
      deploy:
        steps:
        - template: 'template-steps-release.yaml'
          parameters:
            message: '${{ parameters.message }}'
