parameters:
  templateLevel: ''
  message: ''

jobs:
- deployment: HostedVs2017
  displayName: 'Hosted VS2017'

  pool:
    name: 'Hosted VS2017'

  environment: release-with-${{ parameters.templateLevel }}-template

  strategy:
    runOnce:
      deploy:
        steps:
        - task: PowerShell@2
          displayName: 'Echo Greeting in PowerShell'
          inputs:
            targetType: Inline
            script: |
              Write-Host "$(Greeting)"
              Write-Host "${{ parameters.message }}"
          