parameters:
  message: ''

jobs:
- job: HostedVs2017
  displayName: 'Hosted VS2017'
  pool:
    name: 'Hosted VS2017'
  workspace:
    clean: all

  steps:
  - template: 'template-steps-build.yaml'
    parameters:
      message: '${{ parameters.message }}'
